name: "sast-scan"

on:
  push:
    branches: [githubcicd]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci --force

      - name: Download OWASP Dependency Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
          unzip dependency-check-12.1.0-release.zip

      - name: Run scan with ODC
        run: |
          dependency-check/bin/dependency-check.sh \
            --project "bitcoin" \
            --scan . \
            --format HTML \
            --out ./ODC-report \
            --failOnCVSS 11 || true

      - name: Archive ODC report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: ./ODC-report
